#!/usr/bin/env python3

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot raw vs reconstructed three-phase EMT signals and their errors."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("threephase_dp_comparison.csv"),
        help="Path to the comparison CSV generated by compare_threephase_dp_reconstruction.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("threephase_dp_comparison.png"),
        help="Output PNG path.",
    )
    parser.add_argument(
        "--x-axis",
        choices=("sequence", "time"),
        default="sequence",
        help="Use sequence number or time on the x-axis.",
    )
    parser.add_argument(
        "--harmonics",
        default="1",
        help="Comma-separated physical harmonic orders represented in the reconstruction.",
    )
    return parser.parse_args()


def parse_harmonics(spec: str):
    return [int(part.strip()) for part in spec.split(",") if part.strip()]


def plot_comparison(csv_path: Path, output_path: Path, x_axis: str, harmonics: list[int]):
    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()

    phases = []
    for column in df.columns:
        if column in ("sequence", "time_s"):
            continue
        if column.endswith("_reconstructed") or column.endswith("_error"):
            continue
        phases.append(column)

    x = df["sequence"] if x_axis == "sequence" and "sequence" in df.columns else df["time_s"]
    x_label = "Sequence" if x_axis == "sequence" and "sequence" in df.columns else "Time [s]"
    fig, axes = plt.subplots(len(phases), 2, figsize=(14, 3.6 * len(phases)), sharex="col")
    if len(phases) == 1:
        axes = [axes]

    harmonic_label = ", ".join(str(h) for h in harmonics)
    fig.suptitle(
        f"Three-phase DP reconstruction comparison (physical harmonics: {harmonic_label})"
    )

    for row_axes, phase in zip(axes, phases):
        ax_signal, ax_error = row_axes

        ax_signal.plot(x, df[phase], label="original", linewidth=1.0)
        ax_signal.plot(
            x,
            df[f"{phase}_reconstructed"],
            label=f"reconstructed (h={harmonic_label})",
            linewidth=1.0,
        )
        ax_signal.set_title(f"{phase}: original vs reconstructed")
        ax_signal.set_ylabel("Amplitude")
        ax_signal.grid(True)
        ax_signal.legend(loc="upper right")

        ax_error.plot(x, df[f"{phase}_error"], color="tab:red", linewidth=1.0)
        ax_error.set_title(f"{phase}: reconstructed - original")
        ax_error.set_ylabel("Error")
        ax_error.grid(True)

    axes[-1][0].set_xlabel(x_label)
    axes[-1][1].set_xlabel(x_label)
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    plt.close(fig)


def main():
    args = parse_args()
    plot_comparison(args.input, args.output, args.x_axis, parse_harmonics(args.harmonics))
    print(f"Wrote plot to {args.output}")


if __name__ == "__main__":
    main()
