nodes = {
    signal_node = {
        type = "signal.v2"

        rate = 1000.0

        # Wait between emitting each sample
        realtime = true

        # Only emit 1000 samples, then stop
        limit = 10000

        in = {
            signals = (
                { name = "sine1" signal = "sine" amplitude = 100.0 frequency = 10 offset = 1.0 }
            )
        }
    }
    socket1 = {
        type = "socket"
        layer = "udp"

        in = {
            address = "*:12000"
        }
        out = {
            address = "127.0.0.1:12001"
        }
    }
}

paths = (
    {
        in = "signal_node"
        out = "socket1"
    }
) 
