# SPDX-FileCopyrightText: 2021-2024 Institute for Automation of Complex Power Systems, EONERC, RWTH Aachen University
# SPDX-License-Identifier: MPL-2.0

services:
  dpsim:
    build:
      context: ../../../../ #dpsim top-level folder
      dockerfile: packaging/Docker/Dockerfile.dev
    environment:
      PYTHONPATH: /dpsim/build:/dpsim/build/Source/Python:/dpsim/Source/Python
    ports:
      - "8888:8888"
    volumes:
      - ../../../../:/dpsim
    privileged: true
    stdin_open: true
    tty: true
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    stdin_open: true
    tty: true
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
