# SPDX-FileCopyrightText: 2022-2025 Institute for Automation of Complex Power Systems, EONERC, RWTH Aachen University
# SPDX-License-Identifier: MPL-2.0

FROM ubuntu:latest

RUN apt update
RUN apt install -y git golang curl sudo
RUN curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - && \
	sudo apt-get install -y nodejs
RUN go install -tags extended github.com/gohugoio/hugo@latest
RUN cp /root/go/bin/hugo /usr/bin/hugo
EXPOSE 1313/tcp

WORKDIR /dpsim/docs/hugo
