nodes = {
    signal_node = {
        type = "signal.v2"

        rate = 20000.0
        realtime = false
        limit = 100000

        in = {
            signals = (
                { name = "VA_emt", signal = "sine", amplitude = 100.0, frequency = 60, phase = 0.0 },
                { name = "VB_emt", signal = "sine", amplitude = 100.0, frequency = 60, phase = -120.0 },
                { name = "VC_emt", signal = "sine", amplitude = 100.0, frequency = 60, phase = 120.0 }
            )
        }
    }

    raw_file_node = {
        type = "file"
        uri = "villas-conf2-threephase-roundtrip-raw.csv"
        format = "csv"

        out = {
            flush = false
            buffer_size = 0
        }
    }

    recon_file_node = {
        type = "file"
        uri = "villas-conf2-threephase-roundtrip-reconstructed.csv"
        format = "csv"

        out = {
            flush = false
            buffer_size = 0
        }
    }
}

paths = (
    {
        in = "signal_node"
        out = "raw_file_node"
    },
    {
        in = "signal_node"
        out = "recon_file_node"
        signals = (
            { name = "VA_emt", type = "float", unit = "V" },
            { name = "VB_emt", type = "float", unit = "V" },
            { name = "VC_emt", type = "float", unit = "V" }
        )
        hooks = (
            {
                type = "dp"
                signal = "VA_emt"
                f0 = 60
                dt = 0.00005
                harmonics = [ 1 ]
                inverse = false
            },
            {
                type = "dp"
                signal = "VB_emt"
                f0 = 60
                dt = 0.00005
                harmonics = [ 1 ]
                inverse = false
            },
            {
                type = "dp"
                signal = "VC_emt"
                f0 = 60
                dt = 0.00005
                harmonics = [ 1 ]
                inverse = false
            },
            {
                type = "dp"
                signal = 0
                f0 = 60
                dt = 0.00005
                harmonics = [ 1 ]
                inverse = true
            },
            {
                type = "dp"
                signal = 1
                f0 = 60
                dt = 0.00005
                harmonics = [ 1 ]
                inverse = true
            },
            {
                type = "dp"
                signal = 2
                f0 = 60
                dt = 0.00005
                harmonics = [ 1 ]
                inverse = true
            }
        )
    }
)
