nodes = {
    signal_node = {
        type = "signal.v2"

        rate = 20000.0

        # Wait between emitting each sample
        realtime = false

        # Only emit 1000 samples, then stop
        limit = 100000

        in = {
            signals = (
                { name = "VA_emt", signal = "sine", amplitude = 100.0, frequency = 60, phase = 0.0 },
                { name = "VB_emt", signal = "sine", amplitude = 100.0, frequency = 60, phase = -120.0 },
                { name = "VC_emt", signal = "sine", amplitude = 100.0, frequency = 60, phase = 120.0 }
            )
        }
    }

    raw_file_node = {
        type = "file"
        uri = "villas-conf2-threephase-raw.csv"
        format = "csv"

        out = {
            flush = false
            buffer_size = 0
        }
    }

    dp_file_node = {
        type = "file"
        uri = "villas-conf2-threephase-dp.csv"
        format = "csv"

        out = {
            flush = false
            buffer_size = 0
        }
    }
}

paths = (
    {
        in = "signal_node"
        out = "raw_file_node"
        hooks = (
            {
                type = "print"
                format = "villas.human"
                prefix = "[raw ]"
            }
        )
    },
    {
        in = "signal_node"
        out = "dp_file_node"
        signals = (
            { name = "VA_emt", type = "float", unit = "V" },
            { name = "VB_emt", type = "float", unit = "V" },
            { name = "VC_emt", type = "float", unit = "V" }
        )
        output = {
            signals = (
                { name = "VA_dp", type = "complex", unit = "V" },
                { name = "VB_dp", type = "complex", unit = "V" },
                { name = "VC_dp", type = "complex", unit = "V" }
            )
        }
        hooks = (
            {
                type = "dp"
                signal = "VA_emt"
                f0 = 60
                dt = 0.00005
                harmonics = [ 1 ]
                inverse = false
            },
            {
                type = "dp"
                signal = "VB_emt"
                f0 = 60
                dt = 0.00005
                harmonics = [ 1 ]
                inverse = false
            },
            {
                type = "dp"
                signal = "VC_emt"
                f0 = 60
                dt = 0.00005
                harmonics = [ 1 ]
                inverse = false
            },
            {
                type = "print"
                format = "villas.human"
                prefix = "[dp  ]"
            }
        )
    }
)
