nodes = {
    dp_in = {
        type = "shmem"

        in = {
            name = "/dpsim.dp-follower-to-bridge"
            signals = (
                { name = "seq_from_self_dp", type = "integer" },
                { name = "seq_from_external_dp", type = "integer" },
                { name = "VA_dp", type = "complex", unit = "V" },
                { name = "VB_dp", type = "complex", unit = "V" },
                { name = "VC_dp", type = "complex", unit = "V" }
            )
        }
    }

    emt_out = {
        type = "shmem"

        out = {
            name = "/dpsim.leader-to-follower"
            signals = (
                { name = "seq_to_self_emt", type = "integer" },
                { name = "seq_to_external_emt", type = "integer" },
                { name = "VA_emt", type = "float", unit = "V" },
                { name = "VB_emt", type = "float", unit = "V" },
                { name = "VC_emt", type = "float", unit = "V" }
            )
        }
    }
}

paths = (
    {
        in = "dp_in"
        out = "emt_out"
        signals = (
            { name = "seq_from_self_dp", type = "integer" },
            { name = "seq_from_external_dp", type = "integer" },
            { name = "VA_dp", type = "complex", unit = "V" },
            { name = "VB_dp", type = "complex", unit = "V" },
            { name = "VC_dp", type = "complex", unit = "V" }
        )
        hooks = (
            {
                type = "dp"
                signal = "VA_dp"
                f0 = 60
                dt = 0.00005
                harmonics = [ 0 ]
                inverse = true
            },
            {
                type = "dp"
                signal = "VB_dp"
                f0 = 60
                dt = 0.00005
                harmonics = [ 0 ]
                inverse = true
            },
            {
                type = "dp"
                signal = "VC_dp"
                f0 = 60
                dt = 0.00005
                harmonics = [ 0 ]
                inverse = true
            }
        )
    }
)
