nodes = {
    emt_in = {
        type = "shmem"

        in = {
            name = "/dpsim.follower-to-leader"
            signals = (
                { name = "seq_from_self_emt", type = "integer" },
                { name = "seq_from_external_emt", type = "integer" },
                { name = "IA_emt", type = "float", unit = "A" },
                { name = "IB_emt", type = "float", unit = "A" },
                { name = "IC_emt", type = "float", unit = "A" }
            )
        }
    }

    dp_out = {
        type = "shmem"

        out = {
            name = "/dpsim.bridge-to-dp-follower"
            signals = (
                { name = "seq_to_self_dp", type = "integer" },
                { name = "seq_to_external_dp", type = "integer" },
                { name = "IA_dp", type = "complex", unit = "A" }
            )
        }
    }
}

paths = (
    {
        in = "emt_in"
        out = "dp_out"
        signals = (
            { name = "seq_from_self_emt", type = "integer" },
            { name = "seq_from_external_emt", type = "integer" },
            { name = "IA_emt", type = "float", unit = "A" }
        )
        hooks = (
            {
                type = "dp"
                signal = "IA_emt"
                f0 = 60
                dt = 0.00005
                harmonics = [ 0 ]
                inverse = false
            }
        )
    }
)
